apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    apps: nginx
spec:
  containers:
  - name: nginx
    image: myimage
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80

...
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    apps: nginx
  ports:
  - nodePort: 30007
    port: 80
    protocol: TCP
    targetPort: 80
